# Generated by Django 5.2.4 on 2025-11-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vehicle_repayment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='weekly_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
