# Generated by Django 5.2.4 on 2025-11-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vehicle_weekly_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='bank_statement_file',
            field=models.URLField(blank=True, help_text='URL to uploaded bank statement file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='bank_statement_summary',
            field=models.TextField(blank=True, help_text='Summary of bank statement including average balance, transaction patterns, etc.', null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
